apiVersion: v1
kind: Pod
metadata:
  name: planner
  labels:
    app: planner
spec:
  containers:
  - name: planner
    image: aaronkolins77/planner
    ports:
    - containerPort: 1337
    env:
    - name: TASKS
      value: "4"