apiVersion: v1
kind: Pod
metadata:
  name: planner
  labels:
    purpose: plan
spec:
  containers:
    - name: planner
      image: localhost:5000/planner
      imagePullPolicy: IfNotPresent
      env:
        - name: TASKS
          value: '20'
