apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-add
  labels:
    app: worker
    specialization: add
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
      specialization: add
  template:
    metadata:
      labels:
        app: worker
        specialization: add
    spec:
      containers:
        - name: worker
          image: aaronkolins77/worker
          ports:
            - containerPort: 3000
          env:
            - name: ADDRESS
              value: 'http://worker-add.default.svc.cluster.local:1337'
            - name: PORT
              value: '3000'
            - name: MULT
              value: 'false'
            - name: ADD
              value: 'true'
            - name: PLANNER
              value: 'http://planner.default.svc.cluster.local:8080'
