apiVersion: v1
kind: Service
metadata:
  name: worker-add
spec:
  selector:
    app: worker
    specialization: add
  ports:
    - port: 1337
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: worker-mult
spec:
  selector:
    app: worker
    specialization: mult
  ports:
    - port: 1337
      targetPort: 3000
  type: LoadBalancer
