apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: aaronkolins77/worker
        ports:
        - containerPort: 3000
        env:
        - name: ADDRESS
          value: 'http://worker.default.svc.cluster.local:3000'
        - name: PORT
          value: '3000'
        - name: MULT
          value: 'true'
        - name: ADD
          value: 'true'
        - name: PLANNER
          value: 'http://planner.default.svc.cluster.local:8080'
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
  - port: 1337
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
