apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    app: worker
spec:
  containers:
  - name: worker
    image: aaronkolins77/worker
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    - name: MULT
      value: "true"
    - name: ADD
      value: "true"
    - name: PLANNER
      value: "http://planner:3000"